# Ansible playbook to install Magento on a AWS Linux AMI.
# Make sure you have the right private-key used on AWS to connect to the ec2.
# Run: ansible-playbook -i hosts playbooks/magento.yml

---
- name: provisioning an instance at Google Cloud
  hosts: provisioning
  gather_facts: no
  connection: local
  roles:
  - gcp

- name: manage new instance
  hosts: magento
  connection: ssh
  user: "{{ gcp_ssh_username }}"
  become: True
  roles:
    - common
    - mysql
    - httpd
    - php
    - varnish
    - magento
