---
- name: install httpd on CentOS/RHEL
  yum:
    name: 
      - httpd24-httpd
      - httpd24-httpd-tools
      - httpd24-mod_ssl
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install httpd on other OS
  yum:
    name: 
      - httpd24
      - httpd24-tools
      - mod24_ssl
    state: present
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Red Hat Enterprise Linux'

- set_fact:
    httpd_base_dir: /opt/rh/httpd24/root
    httpd_service: httpd24-httpd
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- set_fact:
    httpd_base_dir: ""
    httpd_service: httpd
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Red Hat Enterprise Linux'

- name: remove unused modules
  file: 
    state: absent
    path: "{{ item }}"
  with_items:
  - "{{ httpd_base_dir }}/etc/httpd/conf.d/autoindex.conf"
  - "{{ httpd_base_dir }}/etc/httpd/conf.d/welcome.conf"

- name: change dirs permissions
  file:
    path: "{{ httpd_base_dir }}/usr/share/httpd"
    recurse: yes
    mode: u=rwX,g=rwX,o=rX
    owner: "{{ server_web_user }}"
    group: root

- name: create httpd configuration file
  template: src=magento.conf.j2 dest={{ httpd_base_dir }}/etc/httpd/conf.d/magento.conf
  notify:
  - restart httpd

- name: httpd initial start
  service: name={{ httpd_service }} state=started enabled=yes
