---
- name: install httpd on CentOS/RHEL
  yum:
    name: 
      - httpd
      - httpd-tools
      - mod_ssl
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: install httpd on other OS
  yum:
    name: 
      - httpd24
      - httpd24-tools
      - mod24_ssl
    state: present
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Red Hat Enterprise Linux'

- name: remove unused modules
  file: 
    state: absent
    path:
    - /etc/httpd/conf.d/autoindex.conf
    - /etc/httpd/conf.d/welcome.conf

- name: create httpd configuration file
  template: src=magento.conf.j2 dest=/etc/httpd/conf.d/magento.conf
  notify:
  - restart httpd

- name: httpd initial start
  service: name=httpd state=started enabled=yes
