---
- name: install epel repository
  yum: name=epel-release state=present

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: set ulimit
  pam_limits:
    domain: "{{ server_web_user }}"
    limit_type: soft
    limit_item: stack
    value: 65536

- name: verify if swap exists
  stat:
    path: "{{ server_swap_path }}"
  register: swap_file_presence

- name: create swapfile
  command: "dd if=/dev/zero of={{ server_swap_path }} bs=10M count=200"
  register: write_swapfile
  when: swap_file_presence.stat.exists == False

- name: set swapfile permissions
  file: path="{{ server_swap_path }}" mode=600

- name: build swapfile
  command: "mkswap {{ server_swap_path }}"
  register: create_swapfile
  when: write_swapfile.changed

- name: enable swapfile
  command: "swapon {{ server_swap_path }}"
  when: create_swapfile.changed

- name: add swapfile to /etc/fstab
  lineinfile: dest=/etc/fstab line="{{ server_swap_path }}   none    swap    sw    0   0" state=present
